# -*- coding: utf-8 -*-
"""semantic0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zx_R5QKPwhEZfRVuJXAl4gR1bLTiCL3Q
"""



from google.colab import files # upload zipped

uploaded = files.upload()

import zipfile # Unzip data

zip_path = "/content/[PUB] India_runs_data_and_ai_challenge.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/data")
print("Dataset extracted successfully!")

import os    # See the Files

for root, dirs, files in os.walk("/content/data"):
    for file in files:
        print(os.path.join(root, file))

!pip install sentence-transformers python-docx pandas scikit-learn #Install python libraries

from docx import Document # Read job description

doc = Document("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx")

job_description = ""

for para in doc.paragraphs:
    job_description += para.text + "\n"

print(job_description)

# Load candidates Data sets
import json

candidates = []

with open("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

print("Number of candidates:", len(candidates))

#inspect the first Candidate
candidates[0]

def candidate_to_text(candidate):

    profile = candidate['profile']

    headline = profile.get('headline', '')
    summary = profile.get('summary', '')
    title = profile.get('current_title', '')
    experience = str(profile.get('years_of_experience', ''))

    skills = " ".join(
        skill['name']
        for skill in candidate['skills']
    )

    career = " ".join(
        job['description']
        for job in candidate['career_history']
    )

    text = f"""
    {headline}

    {summary}

    Current Role:
    {title}

    Experience:
    {experience} years

    Skills:
    {skills}

    Career History:
    {career}
    """

    return text

!pip install sentence-transformers # install Sentence transformer

#Load Model
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

# convert all candidates into text
candidate_texts = [candidate_to_text(candidate)for candidate in candidates]

print(candidate_texts[0])

# Generate the job embedding
job_embedding = model.encode(job_description,normalize_embeddings=True)

#define Relevant Keyword
good_keywords = [ "retrieval","ranking","recommendation", "embedding","sentence-transformers", "faiss", "milvus","qdrant","weaviate",
                 "pinecone","elasticsearch","opensearch","llm", "fine-tuning", "lora","peft","rag","vector", "search"]

#create candidate document
def candidate_document(candidate):

    profile = candidate['profile']

    text = ""

    text += profile.get('headline', '') + " "
    text += profile.get('summary', '') + " "

    for job in candidate['career_history']:
        text += job.get('title', '') + " "
        text += job.get('description', '') + " "

    for skill in candidate['skills']:
        text += skill['name'] + " "

    return text.lower()

#filter Candidate
filtered_indices = []

for i, candidate in enumerate(candidates):

    years = candidate['profile']['years_of_experience']

    if years < 4 or years > 10:
        continue

    doc = candidate_document(candidate)

    score = sum(
        keyword in doc
        for keyword in good_keywords
    )

    if score >= 2:
        filtered_indices.append(i)

print("Filtered candidates:", len(filtered_indices))

#Create filter Candidate list
filtered_candidates = [
    candidates[i]
    for i in filtered_indices
]

print(len(filtered_candidates))

# Create candidate Texts
filtered_candidate_texts = [
      candidate_to_text(candidate)
    for candidate in filtered_candidates
]

print(filtered_candidate_texts[0][:1000])

# Generate Embedding
import numpy as np

filtered_embeddings = model.encode(
    filtered_candidate_texts,
    batch_size=512,
    normalize_embeddings=True,
    show_progress_bar=True
)

filtered_embeddings = np.array(filtered_embeddings)

print(filtered_embeddings.shape)

# compute Semantic similarities
similarities = filtered_embeddings @ job_embedding

#Get Top 500 Candidates
top_k = 500

top_indices = np.argsort(similarities)[::-1][:top_k]

print(top_indices[:10])

# Create Top Candidate list
top_candidates = [
    filtered_candidates[i]
    for i in top_indices
]

print(len(top_candidates))

#Skill Score
core_skills = ["embedding","retrieval","ranking","llm","fine-tuning","faiss","milvus",
               "qdrant","weaviate","pinecone","python",  "lora","peft", "search"]

def skill_score(candidate):

    skills = [
        skill['name'].lower()
        for skill in candidate['skills']
    ]

    matches = sum(
        keyword in " ".join(skills)
        for keyword in core_skills
    )

    return matches / len(core_skills)

#Experience Score
def experience_score(candidate):

    years = candidate['profile']['years_of_experience']

    if 5 <= years <= 9:
        return 1.0

    elif 4 <= years < 5:
        return 0.8

    elif 9 < years <= 10:
        return 0.8

    else:
        return 0.4

#redrobe Score
def redrob_score(candidate):

    signals = candidate['redrob_signals']

    score = 0

    if signals['open_to_work_flag']:
        score += 0.2

    score += (
        signals['recruiter_response_rate']
    ) * 0.2

    score += (
        signals['interview_completion_rate']
    ) * 0.2

    score += (
        signals['offer_acceptance_rate']
    ) * 0.2

    score += (
        signals['github_activity_score'] / 100
    ) * 0.2

    return score

#Combine Everything
ranked_candidates = []

for idx in top_indices:

    candidate = filtered_candidates[idx]

    semantic = similarities[idx]

    skill = skill_score(candidate)

    exp = experience_score(candidate)

    redrob = redrob_score(candidate)

    final_score = (
        0.4 * semantic
        + 0.25 * skill
        + 0.15 * exp
        + 0.20 * redrob
    )

    ranked_candidates.append(
        (
            candidate['candidate_id'],
            final_score
        )
    )

# Sort
ranked_candidates.sort(
    key=lambda x: x[1],
    reverse=True
)

ranked_candidates[:10]

#Career History score
good_terms = ["retrieval", "ranking","recommendation","search","embedding",
              "vector","llm","fine-tuning","rag"]

bad_terms = ["speech","tts","asr","computer vision",
             "object detection","robotics"]

def career_score(candidate):

    text = ""

    for job in candidate['career_history']:
        text += " "
        text += job['title'].lower()
        text += " "
        text += job['description'].lower()

    score = 0

    for term in good_terms:
        if term in text:
            score += 1

    for term in bad_terms:
        if term in text:
            score -= 1

    score = max(score, 0)

    return min(score / len(good_terms), 1)

# Consulting Companies penalties
service_companies = ["tcs","infosys","wipro","cognizant","capgemini","accenture"]

def consulting_penalty(candidate):

    companies = [
        job['company'].lower()
        for job in candidate['career_history']
    ]

    count = 0

    for company in companies:
        if any(
            service in company
            for service in service_companies
        ):
            count += 1

    if count == len(companies):
        return 0.3

    return 0

#Improvised Final Score
improved_ranked_candidates = []

for idx in top_indices:

    candidate = filtered_candidates[idx]

    semantic = similarities[idx]

    skill = skill_score(candidate)

    exp = experience_score(candidate)

    redrob = redrob_score(candidate)

    career = career_score(candidate)

    penalty = consulting_penalty(candidate)

    final_score = (
        0.35 * semantic
        + 0.20 * skill
        + 0.15 * exp
        + 0.15 * redrob
        + 0.15 * career
        - penalty
    )

    improved_ranked_candidates.append(
        (
            candidate['candidate_id'],
            final_score
        )
    )

# Sort
improved_ranked_candidates.sort(
    key=lambda x: x[1],
    reverse=True
)

improved_ranked_candidates[:20]

improved_ranked_candidates[:10]

#inspect sample submission
import pandas as pd

sample = pd.read_csv("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv")

sample.head()

submission = pd.DataFrame(
    improved_ranked_candidates,
    columns=['candidate_id', 'score']
)

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

top_100 = improved_ranked_candidates[:100]

submission_rows = []

for rank, (candidate_id, score) in enumerate(top_100, start=1):

    submission_rows.append({
        "candidate_id": candidate_id,
        "rank": rank,
        "score": float(score),
        "reasoning":
        "Strong semantic match with required AI retrieval/ranking skills, relevant experience and positive platform signals."
    })

submission = pd.DataFrame(submission_rows)

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

submission.to_csv(
    "submission.csv",
    index=False
)

print("Submission saved successfully!")

!find /content -name "validate_submission.py"

!python "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py" submission.csv